module.exports = {
  parser: 'babel-eslint',
  env: {
    browser: true,
  },
  rules: {
    'semi': ['error', 'always'],
    'quotes': ['error', 'single'],
    'no-extra-parens': ['warn', 'all'],
    'template-curly-spacing': ['warn', 'never'],
    'sort-imports': ['warn'],
    'rest-spread-spacing': ['warn'],
    'prefer-template': ['warn'],
    'prefer-spread': ['warn'],
    'prefer-rest-params': 'warn',
    'prefer-const': 'warn',
    'no-var': 'error',
    'no-useless-rename': 'error',
    'no-duplicate-imports': 'warn',
    'no-dupe-class-members': 'error',
    'no-const-assign': 'error',
    'generator-star-spacing': ['warn', 'before'],
    'arrow-spacing': 'warn',
  },
};
